CREATE USER IF NOT EXISTS 'xavierlopez25'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON blog_db.* TO 'xavierlopez25'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS blog_db;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    warframe TEXT NOT NULL,
    build TEXT NOT NULL,
    formas_required INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    image_base64 TEXT
);
